dependencyManagement {
    versions {
        testUtilsVersion="10.1.0-201.1114"
        xldStitchCoreVersion="26.3.0-beta.415"
        deployCliVersion="26.3.0-beta.415"
        xlDeployTrialVersion="26.3.0-beta.415"
        deployTaskEngineVersion="26.3.0-beta.415"
        xlDeployVersion="26.3.0-beta.415"
        xlCliVersion="26.3.0-beta.401"
        xlPlatformVersion="26.3.0-beta.415"
    }
}
