dependencyManagement {
    versions {
        testUtilsVersion="10.1.0-201.1114"
        xldStitchCoreVersion="25.3.8-628.1600"
        deployCliVersion="25.3.8-628.1600"
        xlDeployTrialVersion="25.3.8-628.1600"
        deployTaskEngineVersion="25.3.8-628.1600"
        xlCliVersion="25.3.8-708.956"
        xlDeployVersion="25.3.8-628.1600"
        xlPlatformVersion="25.3.8-628.1600"
    }
}
