dependencyManagement {
    versions {
        testUtilsVersion="10.1.0-201.1114"
        xldStitchCoreVersion="27.1.0-beta.825"
        deployCliVersion="27.1.0-beta.825"
        xlDeployTrialVersion="27.1.0-beta.825"
        deployTaskEngineVersion="27.1.0-beta.825"
        xlDeployVersion="27.1.0-beta.825"
        xlCliVersion="27.1.0-beta.821"
        xlPlatformVersion="27.1.0-beta.825"
    }
}
