
LABEL name="Digital.ai Deploy Operator" \
      vendor="Digital.ai" \
      version="${VERSION}" \
      release="1" \
      summary="Digital.ai Deploy Operator based on helm chart" \
      description="Digital.ai Deploy Operator based on helm chart from https://github.com/digital-ai/deploy-helm-chart"

COPY licenses /licenses
